import { GenresIds } from "./Genres.js";

export default [
  {
    poster: 'img/posters/lordOfRings.jpg',
    title: 'Lord of the Rings',
    priceUsd: 15,
    author: 'J. R. R. Tolkien',
    pages: 643,
    isbn: 'g23iu4gg3',
    genre: GenresIds.FANTASY,
  },
  {
    poster: 'img/posters/discworld.jpg',
    title: 'Discworld',
    priceUsd: 13,
    author: 'Terry Pratchett',
    pages: 726,
    isbn: 'sadg781ds',
    genre: GenresIds.COMIC_FANTASY,
  },
  {
    poster: 'img/posters/theLittlePrince.jpg',
    title: 'The Little Prince',
    priceUsd: 16,
    author: 'Antoine de Saint-Exupery',
    pages: 467,
    isbn: '2hcae7cv',
    //genre: ['Fantasy', 'Novel', GenresIds.CHILDRENS_FICTION],
    genre: GenresIds.CHILDRENS_FICTION,
  },
  {
    poster: 'img/posters/dreamOfTheRedChamber.jpg',
    title: 'Dream of the Red Chamber',
    priceUsd: 15,
    author: 'Cao Xueqin',
    pages: 786,
    isbn: 'uiert7e4ir',
    genre: GenresIds.NOVEL,
  },
  {
    poster: 'img/posters/theHobbit.jpg',
    title: 'The Hobbit',
    priceUsd: 14,
    author: 'J. R. R. Tolkien',
    pages: 871,
    isbn: 'sdy21yiw2',
    genre: GenresIds.FANTASY,
  },
  {
    poster: 'img/posters/andThenThereWereNone.jpg',
    title: 'And Then There Were None',
    priceUsd: 16,
    author: 'Agatha Christie',
    pages: 657,
    isbn: 'hdsa87ks2',
    // genre: ['Mystery', 'Crime', 'Psychological thriller'],
    genre: GenresIds.FICTION,
  },
  {
    poster: 'img/posters/youCanHealYourLife.jpg',
    title: 'You Can Heal Your Life',
    priceUsd: 14,
    author: 'Louise Hay',
    pages: 546,
    isbn: 'id3hi8h1',
    genre: GenresIds.SELF_HELP,
  },
  {
    poster: 'img/posters/lolita.jpg',
    title: 'Lolita',
    priceUsd: 12,
    author: 'Vladimir Nabokov',
    pages: 621,
    isbn: 'hadh37ihs',
    genre: GenresIds.NOVEL,
  },
  {
    poster: 'img/posters/heidi.jpg',
    title: 'Heidi',
    priceUsd: 13,
    author: 'Johana Spyri',
    pages: 573,
    isbn: 'gsah54k2',
    genre: GenresIds.CHILDRENS_FICTION,
  },
  {
    poster: 'img/posters/watershipDown.jpg',
    title: 'Watership Down',
    priceUsd: 15,
    author: 'Richard Adams',
    pages: 836,
    isbn: 'hsaofh72af',
    genre: GenresIds.FANTASY,
  },
]
